import { TYPE_ACT, TYPE_ANALYZE, TYPE_TRANSLATE } from '../../constants/command.js';
import COMMAND_ACT_ADVISE from './act-advise.js';
import COMMAND_ACT_APOLOGIZE from './act-apologize.js';
import COMMAND_ACT_BLAME from './act-blame.js';
import COMMAND_ACT_COMFORT from './act-comfort.js';
import COMMAND_ACT_COMPLAIN from './act-complain.js';
import COMMAND_ACT_ENCOURAGE from './act-encourage.js';
import COMMAND_ACT_LAUGH from './act-laugh.js';
import COMMAND_ACT_SUM from './act-sum.js';
import COMMAND_ANALYZE_LITERARILY from './analyze-literarily.js';
import COMMAND_ANALYZE_MATHEMATICALLY from './analyze-mathematically.js';
import COMMAND_ANALYZE_NUMEROLOGICALLY from './analyze-numerologically.js';
import COMMAND_ANALYZE_PHILOSOPHICALLY from './analyze-philosophically.js';
import COMMAND_ANALYZE_PSYCHOLOGICALLY from './analyze-psychologically.js';
import COMMAND_ANALYZE from './analyze.js';
import Command from './Command.js';
import COMMAND_SYS_ACTIVATE from './sys-activate.js';
import COMMAND_SYS_COMMAND from './sys-command.js';
import COMMAND_SYS_CONTINUE from './sys-continue.js';
import COMMAND_SYS_DEACTIVATE from './sys-deactivate.js';
import COMMAND_SYS_DEPLOY from './sys-deploy.js';
import COMMAND_SYS_DOC from './sys-doc.js';
import COMMAND_SYS_DRAW_DEMO from './sys-draw-demo.js';
import COMMAND_SYS_DRAW from './sys-draw.js';
import COMMAND_SYS_REPORT from './sys-report.js';
import COMMAND_SYS_SUMMON_DEMO from './sys-summon-demo.js';
import COMMAND_SYS_TALK_DEMO from './sys-talk-demo.js';
import COMMAND_SYS_TALK from './sys-talk.js';
import COMMAND_TRANSLATE_TO_EN from './sys-translate-to-en.js';
import COMMAND_SYS_VERSION from './sys-version.js';

export const ALL_COMMANDS = [
  COMMAND_ANALYZE,
  COMMAND_ANALYZE_LITERARILY,
  COMMAND_ANALYZE_MATHEMATICALLY,
  COMMAND_ANALYZE_NUMEROLOGICALLY,
  COMMAND_ANALYZE_PHILOSOPHICALLY,
  COMMAND_ANALYZE_PSYCHOLOGICALLY,
  COMMAND_ACT_ADVISE,
  COMMAND_ACT_APOLOGIZE,
  COMMAND_ACT_BLAME,
  COMMAND_ACT_COMFORT,
  COMMAND_ACT_COMPLAIN,
  COMMAND_ACT_LAUGH,
  COMMAND_ACT_ENCOURAGE,
  COMMAND_ACT_SUM,
  COMMAND_SYS_ACTIVATE,
  COMMAND_SYS_COMMAND,
  COMMAND_SYS_CONTINUE,
  COMMAND_SYS_DEACTIVATE,
  COMMAND_SYS_DEPLOY,
  COMMAND_SYS_DOC,
  COMMAND_SYS_DRAW,
  COMMAND_SYS_DRAW_DEMO,
  COMMAND_SYS_REPORT,
  COMMAND_SYS_SUMMON_DEMO,
  COMMAND_SYS_TALK,
  COMMAND_SYS_TALK_DEMO,
  COMMAND_SYS_VERSION,
  COMMAND_TRANSLATE_TO_EN,
];

export const INFO_COMMANDS = [
  COMMAND_SYS_VERSION,
  COMMAND_SYS_DOC,
  COMMAND_SYS_REPORT,
];

export const GENERAL_COMMANDS = [
  COMMAND_SYS_SUMMON_DEMO,
  COMMAND_SYS_TALK_DEMO,
  COMMAND_SYS_DRAW_DEMO,
  COMMAND_ACT_SUM,
  COMMAND_ANALYZE,
  COMMAND_SYS_DEPLOY,
];

export const ENQUIRE_COMMANDS = ALL_COMMANDS.filter(({ type }) => (
  type === TYPE_ACT
  || type === TYPE_ANALYZE
  || type === TYPE_TRANSLATE
));

export {
  COMMAND_ACT_ADVISE,
  COMMAND_ACT_APOLOGIZE,
  COMMAND_ACT_BLAME,
  COMMAND_ACT_COMFORT,
  COMMAND_ACT_COMPLAIN,
  COMMAND_ACT_ENCOURAGE,
  COMMAND_ACT_LAUGH,
  COMMAND_ACT_SUM,
  COMMAND_ANALYZE_LITERARILY,
  COMMAND_ANALYZE_MATHEMATICALLY,
  COMMAND_ANALYZE_NUMEROLOGICALLY,
  COMMAND_ANALYZE_PHILOSOPHICALLY,
  COMMAND_ANALYZE_PSYCHOLOGICALLY,
  COMMAND_ANALYZE,
  Command,
  COMMAND_SYS_ACTIVATE,
  COMMAND_SYS_COMMAND,
  COMMAND_SYS_CONTINUE,
  COMMAND_SYS_DEACTIVATE,
  COMMAND_SYS_DEPLOY,
  COMMAND_SYS_DOC,
  COMMAND_SYS_DRAW_DEMO,
  COMMAND_SYS_DRAW,
  COMMAND_SYS_REPORT,
  COMMAND_SYS_SUMMON_DEMO,
  COMMAND_SYS_TALK_DEMO,
  COMMAND_SYS_TALK,
  COMMAND_TRANSLATE_TO_EN,
  COMMAND_SYS_VERSION,
};
